### Assignment for the week 3/5-3/6

In [80]:
import numpy as np
import pandas as pd

In [81]:
twoDarray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(twoDarray))
print(twoDarray.shape)
print(twoDarray.ndim)


<class 'numpy.ndarray'>
(2, 5)
2


In [82]:
list2 = np.arange(1,21)
print(list2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [83]:
list2[10:15]

array([11, 12, 13, 14, 15])

In [84]:
list1=np.arange(10)
array1= slice(2,9)
print (list1[array1])
array2 = slice(2,9,2)
print(list1[array2])
print(len(list1))

[2 3 4 5 6 7 8]
[2 4 6 8]
10


### Broadcasting

In [85]:
a=np.array([10,20,30,40,50,60,70])
b=np.array([1,2,3,4,5,6,7])
a1=np.add(a,b)
print(a1)
a2=np.subtract(a,b)
print(a2)
a3=np.multiply(a,b)
print(a3)
a4=np.divide(a,b)
print(a4.astype(int))

[11 22 33 44 55 66 77]
[ 9 18 27 36 45 54 63]
[ 10  40  90 160 250 360 490]
[10 10 10 10 10 10 10]


In [86]:
a=np.array([10,20,30])
b=np.array([1,2,3,4])
a1=np.add(a,b)
print(a1)
a2=np.subtract(a,b)
print(a2)
a3=np.multiply(a,b)
print(a3)
a4=np.divide(a,b)
print(a4.astype(int))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a1=np.array([[1,2,3,4],[4,5,6,7]])
b1=np.array([[2,3,4,4],[2,5,6,7]])
np.hstack((a1,b1))

In [ ]:
np.vstack((a1,b1))

In [ ]:
a1=np.array([[1,2,3,4],
             [4,5,6,7]])
b1=np.array([[2,3,4,4],
             [2,5,6,7]])
np.append(a1,b1, axis=0)

In [ ]:
np.append(a1,b1, axis=1)

In [ ]:
%autosave 1

In [ ]:
list1=[[0,1,2,3],
       [1,2,3,4],
       [2,3,4,5],
       [3,4,5,6],
       [4,5,6,7],
       [5,6,7,8],
       [6,7,8,9],
       [7,8,9,9]]

In [ ]:
pd.DataFrame(list1, columns=['c1','c2','c3','c4'])

In [ ]:
pd.DataFrame(list(list1), columns=['c1','c2','c3','c4'])

In [ ]:
dict = {'state': ['CA','TX','OH','NY'], 
         'city': ['SFO','Dallas','Columbus','NYC'], 
         'zip': [91222,29933,43222,11001],
         'weather':[78,72,12,9],
        'laguage':['EN','TL','EN','SP'],
        'population':[500,400,100,600],
        'timezone':['PST','CST','EST','EST']}
df4 = pd.DataFrame(dict)
df4


In [ ]:
df4.loc[0:2,['state','zip']]

In [ ]:
df4.iloc[0:2, [0, 2]]

### check notnull in a column

In [ ]:
print(df4['zip'].notnull())

In [ ]:
list1=[[0,1,2,3],
       [1,3,4],
       [2,3,4,5],
       [3,4,6],
       [4,5,6,7]]
df1=pd.DataFrame(list1)
print(df1)
print(df1.fillna(100)) 

In [ ]:
list1=[[0,1,2,3],
       [1,3,4],
       [2,3,4,5],
       [3,4,6],
       [4,5,6,7]]
df1=pd.DataFrame(list1)
df1


In [ ]:
df1.dropna(inplace=True)
df1

### Aggregation

In [ ]:
dictionary = {'Age': [25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
              'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
              'Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
              'Validation':[1,1,1 ,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}
index_labels=['r1','r2','r3','r4','r5','r6','r7','r8','r9','r10','r11','r12','r13','r14','r15','r16','r17']
dframe=pd.DataFrame(dictionary, index=index_labels)
dframe

In [ ]:
dframe.groupby(["Region"])["Age"].mean()

In [ ]:
dframe.groupby(['Hair Color'])['Age','Validation'].sum()

In [ ]:
dframe.groupby(["Region"])["Age"].median()

In [121]:
dt1 = {'Age': [25,30,45,35,33,35,25,52],
              'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown'],
              'Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast'],
              'Validation':[1,1,1 ,0,0,0,0,0]}
dfleft=pd.DataFrame(dt1)
dfleft

Age Hair Color     Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0

In [105]:
dt2 = {'Age': [24,48,22,27,28,21,51,23],
              'Hair Color':['Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
              'Region':['Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
              'Validation':[1,1,1 ,0,0,0,0,0]}
dfright=pd.DataFrame(dt2)
dfright

Age Hair Color     Region  Validation
0   24      Blond  Northeast           1
1   48      Black  Southwest           1
2   22      Black  Southwest           1
3   27      Brown  Northeast           0
4   28      Black  Southeast           0
5   21      Blond  Southeast           0
6   51      Black  Northwest           0
7   23      Brown  Southeast           0

In [123]:
pd.merge(dfleft, dfright, on='Validation') # need to check merge, seems it has some issues

Age_x Hair Color_x   Region_x  Validation  Age_y Hair Color_y   Region_y
0      25        Black  Southwest           1     24        Blond  Northeast
1      25        Black  Southwest           1     48        Black  Southwest
2      25        Black  Southwest           1     22        Black  Southwest
3      30        Black  Northwest           1     24        Blond  Northeast
4      30        Black  Northwest           1     48        Black  Southwest
5      30        Black  Northwest           1     22        Black  Southwest
6      45          Red  Northeast           1     24        Blond  Northeast
7      45          Red  Northeast           1     48        Black  Southwest
8      45          Red  Northeast           1     22        Black  Southwest
9      35        Blond  Southwest           0     27        Brown  Northeast
10     35        Blond  Southwest           0     28        Black  Southeast
11     35        Blond  Southwest           0     21        Blond  Southeast
12     35        Blond  Southwest           0     51        Black  Northwest
13     35        Blond  Southwest           0     23        Brown  Southeast
14     33        Brown  Southwest           0     27        Brown  Northeast
15     33        Brown  Southwest           0     28        Black  Southeast
16     33        Brown  Southwest           0     21        Blond  Southeast
17     33        Brown  Southwest           0     51        Black  Northwest
18     33        Brown  Southwest           0     23        Brown  Southeast
19     35        Brown  Northeast           0     27        Brown  Northeast
20     35        Brown  Northeast           0     28        Black  Southeast
21     35        Brown  Northeast           0     21        Blond  Southeast
22     35        Brown  Northeast           0     51        Black  Northwest
23     35        Brown  Northeast           0     23        Brown  Southeast
24     25        Black  Southwest           0     27        Brown  Northeast
25     25        Black  Southwest           0     28        Black  Southeast
26     25        Black  Southwest           0     21        Blond  Southeast
27     25        Black  Southwest           0     51        Black  Northwest
28     25        Black  Southwest           0     23        Brown  Southeast
29     52        Brown  Southeast           0     27        Brown  Northeast
30     52        Brown  Southeast           0     28        Black  Southeast
31     52        Brown  Southeast           0     21        Blond  Southeast
32     52        Brown  Southeast           0     51        Black  Northwest
33     52        Brown  Southeast           0     23        Brown  Southeast

In [108]:
pd.merge(dfleft, dfright, on="Validation", how="left")

Age_x Hair Color_x   Region_x  Validation  Age_y Hair Color_y   Region_y
0      25        Black  Southwest           1     24        Blond  Northeast
1      25        Black  Southwest           1     48        Black  Southwest
2      25        Black  Southwest           1     22        Black  Southwest
3      30        Black  Northwest           1     24        Blond  Northeast
4      30        Black  Northwest           1     48        Black  Southwest
5      30        Black  Northwest           1     22        Black  Southwest
6      45          Red  Northeast           1     24        Blond  Northeast
7      45          Red  Northeast           1     48        Black  Southwest
8      45          Red  Northeast           1     22        Black  Southwest
9      35        Blond  Southwest           0     27        Brown  Northeast
10     35        Blond  Southwest           0     28        Black  Southeast
11     35        Blond  Southwest           0     21        Blond  Southeast
12     35        Blond  Southwest           0     51        Black  Northwest
13     35        Blond  Southwest           0     23        Brown  Southeast
14     33        Brown  Southwest           0     27        Brown  Northeast
15     33        Brown  Southwest           0     28        Black  Southeast
16     33        Brown  Southwest           0     21        Blond  Southeast
17     33        Brown  Southwest           0     51        Black  Northwest
18     33        Brown  Southwest           0     23        Brown  Southeast
19     35        Brown  Northeast           0     27        Brown  Northeast
20     35        Brown  Northeast           0     28        Black  Southeast
21     35        Brown  Northeast           0     21        Blond  Southeast
22     35        Brown  Northeast           0     51        Black  Northwest
23     35        Brown  Northeast           0     23        Brown  Southeast
24     25        Black  Southwest           0     27        Brown  Northeast
25     25        Black  Southwest           0     28        Black  Southeast
26     25        Black  Southwest           0     21        Blond  Southeast
27     25        Black  Southwest           0     51        Black  Northwest
28     25        Black  Southwest           0     23        Brown  Southeast
29     52        Brown  Southeast           0     27        Brown  Northeast
30     52        Brown  Southeast           0     28        Black  Southeast
31     52        Brown  Southeast           0     21        Blond  Southeast
32     52        Brown  Southeast           0     51        Black  Northwest
33     52        Brown  Southeast           0     23        Brown  Southeast

In [109]:
pd.merge(dfleft, dfright, on="Validation", how="right")

Age_x Hair Color_x   Region_x  Validation  Age_y Hair Color_y   Region_y
0      25        Black  Southwest           1     24        Blond  Northeast
1      30        Black  Northwest           1     24        Blond  Northeast
2      45          Red  Northeast           1     24        Blond  Northeast
3      25        Black  Southwest           1     48        Black  Southwest
4      30        Black  Northwest           1     48        Black  Southwest
5      45          Red  Northeast           1     48        Black  Southwest
6      25        Black  Southwest           1     22        Black  Southwest
7      30        Black  Northwest           1     22        Black  Southwest
8      45          Red  Northeast           1     22        Black  Southwest
9      35        Blond  Southwest           0     27        Brown  Northeast
10     33        Brown  Southwest           0     27        Brown  Northeast
11     35        Brown  Northeast           0     27        Brown  Northeast
12     25        Black  Southwest           0     27        Brown  Northeast
13     52        Brown  Southeast           0     27        Brown  Northeast
14     35        Blond  Southwest           0     28        Black  Southeast
15     33        Brown  Southwest           0     28        Black  Southeast
16     35        Brown  Northeast           0     28        Black  Southeast
17     25        Black  Southwest           0     28        Black  Southeast
18     52        Brown  Southeast           0     28        Black  Southeast
19     35        Blond  Southwest           0     21        Blond  Southeast
20     33        Brown  Southwest           0     21        Blond  Southeast
21     35        Brown  Northeast           0     21        Blond  Southeast
22     25        Black  Southwest           0     21        Blond  Southeast
23     52        Brown  Southeast           0     21        Blond  Southeast
24     35        Blond  Southwest           0     51        Black  Northwest
25     33        Brown  Southwest           0     51        Black  Northwest
26     35        Brown  Northeast           0     51        Black  Northwest
27     25        Black  Southwest           0     51        Black  Northwest
28     52        Brown  Southeast           0     51        Black  Northwest
29     35        Blond  Southwest           0     23        Brown  Southeast
30     33        Brown  Southwest           0     23        Brown  Southeast
31     35        Brown  Northeast           0     23        Brown  Southeast
32     25        Black  Southwest           0     23        Brown  Southeast
33     52        Brown  Southeast           0     23        Brown  Southeast

In [111]:
pd.concat([dfleft, dfright], axis=1)

Age Hair Color     Region  Validation  Age Hair Color     Region  \
0   25      Black  Southwest           1   24      Blond  Northeast   
1   30      Black  Northwest           1   48      Black  Southwest   
2   45        Red  Northeast           1   22      Black  Southwest   
3   35      Blond  Southwest           0   27      Brown  Northeast   
4   33      Brown  Southwest           0   28      Black  Southeast   
5   35      Brown  Northeast           0   21      Blond  Southeast   
6   25      Black  Southwest           0   51      Black  Northwest   
7   52      Brown  Southeast           0   23      Brown  Southeast   

   Validation  
0           1  
1           1  
2           1  
3           0  
4           0  
5           0  
6           0  
7           0

In [113]:
pd.concat([dfleft, dfright])

Age Hair Color     Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0
0   24      Blond  Northeast           1
1   48      Black  Southwest           1
2   22      Black  Southwest           1
3   27      Brown  Northeast           0
4   28      Black  Southeast           0
5   21      Blond  Southeast           0
6   51      Black  Northwest           0
7   23      Brown  Southeast           0

### End of Assignment