### Assignment for the week 3/5-3/6

In [ ]:
import numpy as np
import pandas as pd

In [11]:
twoDarray = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(twoDarray))
print(twoDarray.shape)
print(twoDarray.ndim)


<class 'numpy.ndarray'>
(2, 5)
2


In [47]:
list2 = np.arange(1,21)
print(list2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [46]:
list2[10:15]

array([11, 12, 13, 14, 15])

In [29]:
list1=np.arange(10)
array1= slice(2,9)
print (list1[array1])
array2 = slice(2,9,2)
print(list1[array2])
print(len(list1))

[2 3 4 5 6 7 8]
[2 4 6 8]
10


### Broadcasting

In [63]:
a=np.array([10,20,30,40,50,60,70])
b=np.array([1,2,3,4,5,6,7])
a1=np.add(a,b)
print(a1)
a2=np.subtract(a,b)
print(a2)
a3=np.multiply(a,b)
print(a3)
a4=np.divide(a,b)
print(a4.astype(int))

[11 22 33 44 55 66 77]
[ 9 18 27 36 45 54 63]
[ 10  40  90 160 250 360 490]
[10 10 10 10 10 10 10]


In [65]:
a=np.array([10,20,30])
b=np.array([1,2,3,4])
a1=np.add(a,b)
print(a1)
a2=np.subtract(a,b)
print(a2)
a3=np.multiply(a,b)
print(a3)
a4=np.divide(a,b)
print(a4.astype(int))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [69]:
a1=np.array([[1,2,3,4],[4,5,6,7]])
b1=np.array([[2,3,4,4],[2,5,6,7]])
np.hstack((a1,b1))

array([[1, 2, 3, 4, 2, 3, 4, 4],
       [4, 5, 6, 7, 2, 5, 6, 7]])

In [70]:
np.vstack((a1,b1))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 4],
       [2, 5, 6, 7]])

In [73]:
a1=np.array([[1,2,3,4],
             [4,5,6,7]])
b1=np.array([[2,3,4,4],
             [2,5,6,7]])
np.append(a1,b1, axis=0)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 4],
       [2, 5, 6, 7]])

In [74]:
np.append(a1,b1, axis=1)

array([[1, 2, 3, 4, 2, 3, 4, 4],
       [4, 5, 6, 7, 2, 5, 6, 7]])

In [76]:
%autosave 1

Autosaving every 1 seconds


In [78]:
list1=[[0,1,2,3],
       [1,2,3,4],
       [2,3,4,5],
       [3,4,5,6],
       [4,5,6,7],
       [5,6,7,8],
       [6,7,8,9],
       [7,8,9,9]]

In [84]:
pd.DataFrame(list1, columns=['c1','c2','c3','c4'])

c1  c2  c3  c4
0   0   1   2   3
1   1   2   3   4
2   2   3   4   5
3   3   4   5   6
4   4   5   6   7
5   5   6   7   8
6   6   7   8   9
7   7   8   9   9

In [83]:
pd.DataFrame(list(list1), columns=['c1','c2','c3','c4'])

c1  c2  c3  c4
0   0   1   2   3
1   1   2   3   4
2   2   3   4   5
3   3   4   5   6
4   4   5   6   7
5   5   6   7   8
6   6   7   8   9
7   7   8   9   9

In [88]:
dict = {'state': ['CA','TX','OH','NY'], 
         'city': ['SFO','Dallas','Columbus','NYC'], 
         'zip': [91222,29933,43222,11001],
         'weather':[78,72,12,9],
        'laguage':['EN','TL','EN','SP'],
        'population':[500,400,100,600],
        'timezone':['PST','CST','EST','EST']}
df4 = pd.DataFrame(dict)
df4


state      city    zip  weather laguage  population timezone
0    CA       SFO  91222       78      EN         500      PST
1    TX    Dallas  29933       72      TL         400      CST
2    OH  Columbus  43222       12      EN         100      EST
3    NY       NYC  11001        9      SP         600      EST

In [89]:
df4.loc[0:2,['state','zip']]

state    zip
0    CA  91222
1    TX  29933
2    OH  43222

In [104]:
df4.iloc[0:2, [0, 2]]

state    zip
0    CA  91222
1    TX  29933

### check notnull in a column

In [94]:
print(df4['zip'].notnull())

0    True
1    True
2    True
3    True
Name: zip, dtype: bool
